### ISSUE TITLE
livox-sdk version

### ISSUE THREAD

**Issue by juliangaal** [zijiechenrobotics/ig_lio_workspace#1]
which commit of livox sdk is included in docker/Livox-SDK? thank you

**Comment by zijiechenrobotics** [comment]
Thank you for using ig_lio_workspace!
The Livox-SDK is cloned from https://github.com/Livox-SDK/Livox-SDK.
You can replace Livox-SDK with Livox-SDK2 if you use mid-360 or HAP.

**Comment by juliangaal** [comment]
Ah, seeing that the repo hasn't been updated in multiple years, I can understand why you didn't add it as a submodule. Thank you, I am looking forward to trying out ig lio!
